In [1]:
import geopandas as gpd 
import pandas as pd

In [2]:
cities = ["charleroi", "liege", "mons", "namur", "tournai"]
every = pd.DataFrame()
for city in cities:
    df = gpd.read_file(f"../assets/selection/{city}_sel_centroid.json")
    df2 = df.groupby("tx_sector_descr_fr")["raster_value"].median()
    test = pd.merge(df, df2, on='tx_sector_descr_fr')
    test.to_file(f"../data/centroids/{city}_sel_centroid.json", driver="GeoJSON")
    test["city"] = city
    every = pd.concat([every, test], ignore_index=True)

every.to_file(f"../data/centroids/every_city.json", driver="GeoJSON")
every

,centroid_lon,centroid_lat,raster_value_x,tx_sector_descr_fr,REVENU_MOYEN,REVENU_MEDIAN,NOMBRE_HAB,DENSITE_PAR_HECTARE,ms_area_ha,CD_SECTOR,geometry,raster_value_y,city
0,4.456542,50.491876,37.191654,ROBESSE,22419.0,19330.0,161,79.722541,79.721251,52011P19-,POINT (4.45654 50.49188),34.182514,charleroi
1,4.458339,50.491876,35.840679,ROBESSE,22419.0,19330.0,161,79.722541,79.721251,52011P19-,POINT (4.45834 50.49188),34.182514,charleroi
2,4.454745,50.490733,35.779156,ROBESSE,22419.0,19330.0,161,79.722541,79.721251,52011P19-,POINT (4.45475 50.49073),34.182514,charleroi
3,4.456542,50.490733,38.166214,ROBESSE,22419.0,19330.0,161,79.722541,79.721251,52011P19-,POINT (4.45654 50.49073),34.182514,charleroi
4,4.458339,50.490733,34.960114,ROBESSE,22419.0,19330.0,161,79.722541,79.721251,52011P19-,POINT (4.45834 50.49073),34.182514,charleroi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43422,3.294122,50.570677,32.832821,MARECHE,22512.0,14688.0,50,12.608614,12.608415,57081N02-,POINT (3.29412 50.57068),33.780216,tournai
43423,3.290529,50.569536,34.821507,MARECHE,22512.0,14688.0,50,12.608614,12.608415,57081N02-,POINT (3.29053 50.56954),33.780216,tournai
43424,3.290529,50.568395,34.002590,MARECHE,22512.0,14688.0,50,12.608614,12.608415,57081N02-,POINT (3.29053 50.56840),33.780216,tournai
43425,3.290529,50.567254,33.780216,MARECHE,22512.0,14688.0,50,12.608614,12.608415,57081N02-,POINT (3.29053 50.56725),33.780216,tournai
43426,3.290529,50.566113,34.013245,MARECHE,22512.0,14688.0,50,12.608614,12.608415,57081N02-,POINT (3.29053 50.56611),33.780216,tournai

In [3]:
df = gpd.read_file(f"../assets/selection/liege_sel_centroid.json")
df2 = df.groupby("tx_sector_descr_fr")["raster_value"].median()
test = pd.merge(df, df2, on='tx_sector_descr_fr')
test.to_file(f"../data/centroids/liege_sel_centroid.json", driver="GeoJSON")
test

,centroid_lon,centroid_lat,raster_value_x,tx_sector_descr_fr,REVENU_MOYEN,REVENU_MEDIAN,NOMBRE_HAB,DENSITE_PAR_HECTARE,ms_area_ha,CD_SECTOR,geometry,raster_value_y
0,5.541707,50.684648,33.296066,DUPIREUX,25136.0,21175.0,720,58.021888,58.020940,62063L02-,POINT (5.54171 50.68465),34.257603
1,5.543504,50.684648,32.811886,DUPIREUX,25136.0,21175.0,720,58.021888,58.020940,62063L02-,POINT (5.54350 50.68465),34.257603
2,5.545300,50.684648,32.543659,DUPIREUX,25136.0,21175.0,720,58.021888,58.020940,62063L02-,POINT (5.54530 50.68465),34.257603
3,5.547097,50.684648,32.587578,DUPIREUX,25136.0,21175.0,720,58.021888,58.020940,62063L02-,POINT (5.54710 50.68465),34.257603
4,5.539910,50.683509,33.822441,DUPIREUX,25136.0,21175.0,720,58.021888,58.020940,62063L02-,POINT (5.53991 50.68351),34.257603
...,...,...,...,...,...,...,...,...,...,...,...,...
4203,5.559673,50.562689,28.076517,BOIS SAINT-JEAN,31356.0,15155.0,157,217.645614,217.642053,62063H5QA,POINT (5.55967 50.56269),28.174061
4204,5.561470,50.562689,26.811005,BOIS SAINT-JEAN,31356.0,15155.0,157,217.645614,217.642053,62063H5QA,POINT (5.56147 50.56269),28.174061
4205,5.563267,50.562689,28.062582,BOIS SAINT-JEAN,31356.0,15155.0,157,217.645614,217.642053,62063H5QA,POINT (5.56327 50.56269),28.174061
4206,5.552487,50.561548,27.651836,BOIS SAINT-JEAN,31356.0,15155.0,157,217.645614,217.642053,62063H5QA,POINT (5.55249 50.56155),28.174061
4207,5.554283,50.561548,25.870071,BOIS SAINT-JEAN,31356.0,15155.0,157,217.645614,217.642053,62063H5QA,POINT (5.55428 50.56155),28.174061